# Список с врагами лабиринта и их характеристиками
lists_enemy = [[{'name':'Волчья стая', # Обычные атаки
                 'health': 250,
                 'damage': 15,
                 'armor': 50,
                 'dodge': 0.03,
                 'critical_damage': 0,
                 'chance_critical_damage': 0,
                 'skill1': {'name': None,
                            '1hit': None,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': None,
                            'plus_dodge': None
                            }},
                {'name': 'Гоблин с копьем', #Удар копьем 30 урона кд 3 хода
                 'health': 250,
                 'damage': 15,
                 'armor': 50,
                 'dodge': 0.03,
                 'critical_damage': 0,
                 'chance_critical_damage': 0,
                 'skill1': {'name': 'Удар копьём',
                            '1hit': None,
                            'damage': 30,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 3,
                            'plus_dodge': None
                            }
                 },
                {'name':'Иссушенный труп', #Восстановление 15 здоровья кд 3 хода
                 'health': 250,
                 'damage': 15,
                 'armor': 0,
                 'dodge': 0.03,
                 'critical_damage': 0,
                 'chance_critical_damage': 0,
                 'skill1': {'name': 'Лечение',
                            '1hit': None,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': None,
                            'health': 15,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 3,
                            'plus_dodge': None
                            }
                 }],
               [{'name':'Странствующий маг', #Повышение шанса критического урона через 4 хода на 20%
                 'health': 400,
                 'damage': 40,
                 'armor': 100,
                 'dodge': 0.1,
                 'critical_damage': 0,
                 'chance_critical_damage': 0,
                 'skill1': {'name': 'Магия огня',
                            '1hit': None,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': 0.2,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 4,
                            'plus_dodge': None
                            }
                 },
                {'name':'Страж лабиринта', #Восстановление 25 брони раз в 3 хода
                 'health': 600,
                 'damage': 25,
                 'armor': 150,
                 'dodge': 0,
                 'critical_damage': 0,
                 'chance_critical_damage': 0,
                 'skill1': {'name': 'Восстановление пластин',
                            '1hit': None,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': 25,
                            'plus_damage': None,
                            'skill_colldown': 3,
                            'plus_dodge': None
                            }
                 },
                {'name':'Душа грешника', #Проклятие, отнимающее 50 здоровья врага. КД 4 хода
                 'health': 350,
                 'damage': 35,
                 'armor': 100,
                 'dodge': 0.3,
                 'critical_damage': 2,
                 'chance_critical_damage': 0.2,
                 'skill1': {'name': 'Проклятье',
                            '1hit': None,
                            'damage': 50,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 4,
                            'plus_dodge': None
                            }
                 }],

                [{'name':'Тролль', # Двойная атака раз в 4 хода
                  'health': 700,
                  'damage': 30,
                  'armor': 150,
                  'dodge': 0.25,
                  'critical_damage': 0,
                  'chance_critical_damage': 0,
                  'skill1': {'name': 'Двойная атака',
                             '1hit': None,
                             'damage': None,
                             'ignore': False,
                             'crit_damage': None,
                             'health': None,
                             'armor': None,
                             'plus_damage': 30,
                             'skill_colldown': 4,
                             'plus_dodge': None
                             }
                  },
                {'name':'Демон лабиринта', #Повышение шанса уклонения на 15% через 5 ходов боя
                 'health': 650,
                 'damage': 60,
                 'armor': 200,
                 'dodge': 0.2,
                 'critical_damage': 0,
                 'chance_critical_damage': 0,
                 'skill1': {'name': 'Уворотливость',
                            '1hit': None,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 5,
                            'plus_dodge': 0.15}
                 },
                {'name':'Огненный дракон', #Дыхание огнем 50 урона раз в 3 хода
                 'health': 700,
                 'damage': 40,
                 'armor': 400,
                 'dodge': 0.1,
                 'critical_damage': 0,
                 'chance_critical_damage': 0,
                 'skill1': {'name': 'Дыхание огнем',
                            '1hit': None,
                            'damage': 50,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 3,
                            'plus_dodge': None}
                 }],

                [{'name':'Хранитель лабиринта', #Уничтожение артефакта раз в 2 хода  + звуковой удар 50 урона раз в 3 хода + проникнуть в разум и обездвижить раз в 6 ходов
                  'health': 1000,
                  'damage': 40,
                  'armor': 500,
                  'dodge': 0.18,
                  'critical_damage': 0,
                  'chance_critical_damage': 0
                  },
                {'name':'Осколок леса', #Тайминговый босс
                 'health': 3000,
                 'damage': 0,
                 'armor': 0,
                 'dodge': 0,
                 'critical_damage': 0,
                 'chance_critical_damage': 0
                 }]]

# Список с героями и их характеристиками
lists_heroes = [{'name':'Маг',
                 'health': 1300,
                 'damage': 150,
                 'armor': 300,
                 'dodge': 0.13,
                 'critical_damage': 3,
                 'chance_critical_damage': 0.1,
                 'skill1': {'name': 'Превратить врага в безобидную овечку',
                            '1hit': True,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 5},
                 'skill2': {'name': 'Огненная волна - 300 урона врагу',
                            '1hit': False,
                            'damage': 300,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 2}
                 },
                {'name':'Лучник',
                 'health': 1600,
                 'damage': 100,
                 'armor': 400,
                 'dodge': 0.20,
                 'critical_damage': 2,
                 'chance_critical_damage': 0.08,
                 'skill1': {'name': 'Повышает шанс критического урона на 20%.',
                            '1hit': False,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': 0.2,
                            'health': None,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 3},
                 'skill2': {'name': 'Восстанавливает 150 здоровья.',
                            '1hit': False,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': None,
                            'health': 150,
                            'armor': None,
                            'plus_damage': None,
                            'skill_colldown': 4}},


                {'name': 'Воин',
                 'health': 2000,
                 'damage': 100,
                 'armor': 500,
                 'dodge': 0.15,
                 'critical_damage': 2,
                 'chance_critical_damage': 0.05,
                 'skill1': {'name': 'Удар топором - 250 урона и +10 брони в бою',
                            '1hit': False,
                            'damage': 250,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': 10,
                            'plus_damage': None,
                            'skill_colldown': 3},
                 'skill2': {'name': 'Увеличивает урон на 100 в данном бою.',
                            '1hit': False,
                            'damage': None,
                            'ignore': False,
                            'crit_damage': None,
                            'health': None,
                            'armor': None,
                            'plus_damage': 100,
                            'skill_colldown': 3},
}]
#TODO Добавить еще загадок и ключ с уровнем артефакта для награды
# Список с загадками
list_of_mysterys = [
    {'Ножницы':'Их двое, но они одни. Их драму трудно нам понять. Служа всегда, должны они, соединяя, разделять.?'},
    {'Корень':'Он слово или часть его. Он есть у зуба и у ели.Нет у добра его, но, говорят,у зла бывает?'},
    {'Сон':'Слаще мёда, тяжелее железа, в магазине не продаётся, на базаре не покупается.'},
    {'Цветы':'О них часто говорят «они живые», когда они умерли. Ими встречают рождение и провожают в могилу.'},
    {'Смерть':'Все люди равны перед ней. Одна лишь мысль о ней приводит нас в смятение. Мы идём к ней навстречу, вместо того чтобы просто ожидать её.'},
    {'Пчела':'Она трудится с детства до самой смерти, но нет на свете слаще её труда.'},
    {'Время':'Чего всегда не хватает радости, но в избытке у печали?'},
    {'Время':'Оно летит без крыльев, а идёт без ног. Не доверяет никому, но провести его может любой.'},
    {'Паук':'Его интриги очевидны. Великолепен их узор. Он их плетёт не ради красоты, а просто хочет жить.'},
    {'Память':'Если мы не сделали дело, то говорим, что она нас подвела. Оперативная она в железе, а вам тренировать её полезно.'},
    {'Яма':'Чем больше из неё берёшь, тем больше она становится.'}



]

# Список с артефактами
list_of_artefacts = [[{'name': 'Родниковая вода',
                       'description': 'Фляжка с целительной родниковой водой из глубин лабиринта.',
                       'short_desc': 'Восстанавливает 250 здоровья',
                       'add_artefacts': False,
                       'add_artefact_level': None,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': 250,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

                       {'name': "Красный талисман",
                       'description': 'Талисман яркого красного цвета на серебряной цепочке. В ваших руках светится еще сильнее',
                       'short_desc': 'Даёт +5% к вероятности критического урона',
                       'add_artefacts': False,
                       'add_artefact_level': None,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': 0.05,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

                       {'name': 'Оберег медведя',
                       'description': 'Оберег из клыков медведя, украшенный бархатной шерстью. Даже пахнет дичью.',
                       'short_desc': 'Даёт +3 к броне',
                       'add_artefacts': False,
                       'add_artefact_level': None,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': 3,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

                       {'name': 'Золотая кисть',
                       'description': 'Золотая кисть с оперением. Кажется этой кистью писали историю лабиринта.',
                       'short_desc': 'Даёт возможность 1 раз атаковать противника двойным уроном',
                       'add_artefacts': False,
                       'add_artefact_level': None,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': True,
                       'no_miss': False,
                       'rearm': False},

                       {'name': 'Петля времени',
                       'description': 'Странная петля из холщёвой веревки. При попытке развязать - затягивается еще сильнее',
                       'short_desc': 'Даёт возможность откатить время назад до получения урона от атаки врага',
                       'add_artefacts': False,
                       'add_artefact_level': None,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False}],

                     [{'name': 'Браслет короля обезьян ',
                       'description': 'Красивый браслет короля обезьян, украшенный изумрудами и яшмой. Король никогда не промахивался.',
                       'short_desc': 'Даёт возможность на протяжении 1 боя исключить возможность промаха',
                       'add_artefacts': False,
                       'add_artefact_level': None,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': True,
                       'rearm': False},

                       {'name': 'Песочные часы',
                       'description': 'Старенькие песочные часы. Песка почти не осталось из-за разбитой колбы. А если их перевернуть?',
                       'short_desc': 'Даёт возможность откатить все кулдауны способностей 1 раз.',
                       'add_artefacts': False,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': True},

                      {'name': 'Запечатанный ветер',
                       'description': 'Странная баночка, которая шумит как маленький шторм. Крышка плотно запечатана.',
                       'short_desc': 'Даёт +5% к уклонению, но отнимает 100 здоровья',
                       'add_artefacts': False,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': -100,
                       'damage': None,
                       'armor': None,
                       'dodge': 0.05,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False}],

                     [{'name': 'Мистический ларец',
                       'description': 'Ларец, который меняет цвета. То он красный, как кровь, то он белый, как снег.',
                       'short_desc': 'Выдаёт 2 случайных артефакта 1 уровня',
                       'add_artefacts': True,
                       'add_artefact_count': 2,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

                      {'name': 'Джокер',
                       'description': 'Карта с джокером. Её края настолько острые, что одно прикосновение к ним вызывает боль во всём теле.',
                       'short_desc': 'Выдаёт новое умение: Бросок карты - 250 чистого урона сквозь броню с кд в 3 клетки',
                       'add_artefacts': False,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'skill': {'name': 'Джокер',
                                 '1hit': False,
                                 'damage': 250,
                                 'ignore': True,
                                 'crit_damage': None,
                                 'health': None,
                                 'armor': None,
                                 'plus_damage': None,
                                 'skill_colldown': 4},
                       'add_skill': True,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

                     {'name': 'Костяные кубики',
                       'description': 'Игральные кубики выполненные из кости. Грани сточились от времени, а на цифрах 5 и 6 нарисованы черепа.',
                       'short_desc': 'Бросайте кубики. 2-4 - Артефакт 1 уроня / 5-8 - Артефакт 2 уровня / 9-12 - лучше не выбрасывать ',
                       'add_artefacts': True,
                       'add_artefact_count': 2,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

#TODO Если появится вампирские предметы - починить процент вампиризма в добавлении. ( Класс character )
                      {'name': 'Болотная пиявка',
                       'description': 'Магическая болотная пивка. Кто-то рассказывал, что она может передать часть своих свойств, но никогда не отцепится',
                       'short_desc': 'Даёт +10% вампиризма от атак',
                       'add_artefacts': False,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': True,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

                      {'name': 'Кроличья лапка',
                       'description': 'Знаменитый оберег. Поможет избавиться от недоброжелательных животных',
                       'short_desc': 'В бою с любыми животными: Прогоняет животных и не оставляет награды.',
                       'add_artefacts': False,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},
                      ],


                     [{'name': 'Сундук смерти',
                       'description': 'Чёрный сундук с острыми краями. Из него льётся кровь, а не крышке написано "Не открывать!"',
                       'short_desc': 'Может выпасть 1 артефакт любого уровня или убить вас',
                       'add_artefacts': True,
                       'add_artefact_count': 1,
                       'count': 1,
                       'health': -99999,
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},

                      {'name': 'Зелье здоровья',
                       'description': 'Красненькая склянка с приятными запахом. Так хочется её выпить побыстрее.',
                       'short_desc': 'Восстанавливает 50% от вашего здоровья',
                       'add_artefacts': False,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': '50',
                       'damage': None,
                       'armor': None,
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},


                      {'name': 'Набор инструментов лучшего качества',
                       'description': 'Набор кузнечных инструментов. Владелец держал их до последнего, судя по оторванной руке.',
                       'short_desc': 'Восстанавливает 50% от вашей брони.',
                       'add_artefacts': False,
                       'add_artefact_count': None,
                       'count': 1,
                       'health': None,
                       'damage': None,
                       'armor': '50',
                       'dodge': None,
                       'critical_damage': None,
                       'chance_critical_damage': None,
                       'add_skill': False,
                       'double_attack': None,
                       'no_miss': False,
                       'rearm': False},
                      ]]





# Карта лабиринта
maptest = '''
╔═╦═╦═╦═╦═╦═╦═╦═╗
║x║x║x║x║x║x║x║x║ 
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║x║x║x║H║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║x║x║x║1║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║x║x║x║1║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║3║1║꠳║1║?║?║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║x║x║꠳║x║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║?║?║2║2║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║x║x║x║꠴║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║3║2║꠴║2║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║?║x║x║x║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║۩║x║x║x║x║x║x║
╠═╬═╬═╬═╬═╬═╬═╬═╣
║x║x║x║x║x║x║x║x║
╚═╩═╩═╩═╩═╩═╩═╩═╝
'''
# ╔ ╗╚ ╝ ╠ ╣ ╦ ╩ ╬ ═ ║
# map = """
#          ╔══╗
#          ║в1║
#          ╠══╣
#          ║в1║
# ╔══╦══╦══╬══╬══╦══╗
# ║в3║в1║в1║в1║з ║з ║
# ╚══╩══╬══╬══╩══╩══╝
#       ║в2║
# ╔══╦══╬══╬══╗
# ║з ║з ║в1║в2║
# ╚══╩══╩══╬══╣
#          ║12║
# ╔══╦══╦══╬══╣
# ║в3║12║в2║в2║
# ╠══╬══╩══╩══╝
# ║з ║
# ╠══╣
# ║б ║
# ╚══╝
# """
